-- Run with scripts/recovery/db.py psql -X -v ON_ERROR_STOP=1 -f this-file.
-- All synthetic users, articles, appointments and notifications are rolled back.
BEGIN;
CREATE FUNCTION pg_temp.assert_true(ok boolean, message text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF ok IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAILED: %',message; END IF; END; $$;
CREATE FUNCTION pg_temp.denied(statement text) RETURNS boolean LANGUAGE plpgsql AS $$ BEGIN EXECUTE statement; RETURN false; EXCEPTION WHEN OTHERS THEN RETURN true; END; $$;
SELECT set_config('test.author',gen_random_uuid()::text,true),set_config('test.editor',gen_random_uuid()::text,true),set_config('test.stranger',gen_random_uuid()::text,true),set_config('test.owner',(SELECT id::text FROM profiles WHERE role='admin' LIMIT 1),true);
INSERT INTO auth.users(id,email,raw_user_meta_data) SELECT current_setting('test.'||person)::uuid,person||'-'||gen_random_uuid()||'@example.invalid',jsonb_build_object('full_name','Rollback article test') FROM unnest(ARRAY['author','editor','stranger']) person;
INSERT INTO members(auth_user_id,capacity,full_name_ne,phone,email,status) VALUES(current_setting('test.author')::uuid,'party_member','Rollback test','9800000000','rollback@example.invalid','pending');
INSERT INTO members(auth_user_id,capacity,full_name_ne,phone,email,status) VALUES(current_setting('test.editor')::uuid,'party_member','Rollback editor','9800000001','editor-rollback@example.invalid','approved');
INSERT INTO party_appointments(position_id,profile_id,organization_level,unit_name,assigned_by) SELECT id,current_setting('test.editor')::uuid,'central','Rollback test editor',current_setting('test.owner')::uuid FROM party_positions WHERE name='Editor / सम्पादक';
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',current_setting('test.stranger'),true);
SELECT pg_temp.assert_true(NOT can_submit_member_article(),'Google login alone cannot submit');
SELECT pg_temp.assert_true(pg_temp.denied($$SELECT save_member_article(NULL,'Test','This is an article with sufficient length.','',true)$$),'Unregistered save denied');
SELECT set_config('request.jwt.claim.sub',current_setting('test.author'),true);
SELECT pg_temp.assert_true(can_submit_member_article(),'Pending registration can submit');
SELECT set_config('test.article',(save_member_article(NULL,'Rollback test article','This article exists only inside a rolled back transaction.','Test summary',false)->>'id'),true);
SELECT pg_temp.assert_true((SELECT status='draft' AND is_published=false FROM news_items WHERE id=current_setting('test.article')::bigint),'Draft remains private');
UPDATE news_items SET status='published',is_published=true WHERE id=current_setting('test.article')::bigint;
SELECT pg_temp.assert_true((SELECT status='draft' FROM news_items WHERE id=current_setting('test.article')::bigint),'Direct self publication blocked');
SELECT pg_temp.assert_true(pg_temp.denied(format('SELECT review_member_article(%s,''published'','''')',current_setting('test.article'))),'Author cannot review');
SELECT save_member_article(current_setting('test.article')::bigint,'Rollback test article','This article exists only inside a rolled back transaction.','Test summary',true);
SELECT pg_temp.assert_true(pg_temp.denied(format('SELECT save_member_article(%s,''Changed'',''This is enough body text for an article.'','''',true)',current_setting('test.article'))),'Submitted content cannot change during review');
SELECT set_config('request.jwt.claim.sub',current_setting('test.stranger'),true);
SELECT pg_temp.assert_true(NOT EXISTS(SELECT 1 FROM news_items WHERE id=current_setting('test.article')::bigint),'Other member cannot read submission');
SELECT pg_temp.assert_true(pg_temp.denied(format('SELECT save_member_article(%s,''Stolen'',''This is enough body text for an article.'','''',false)',current_setting('test.article'))),'Other member cannot edit');
SELECT pg_temp.assert_true(pg_temp.denied(format($q$INSERT INTO notifications(user_id,type,title) VALUES('%s','article_approved','Forged')$q$,current_setting('test.author'))),'Client cannot forge review notification');
SELECT set_config('request.jwt.claim.sub',current_setting('test.editor'),true);
SELECT set_config('test.editor_article',(save_member_article(NULL,'Editor rollback article','This editor article is submitted only in a rollback transaction.','',true)->>'id'),true);
SELECT pg_temp.assert_true(pg_temp.denied(format('SELECT review_member_article(%s,''published'','''')',current_setting('test.editor_article'))),'Editor cannot approve their own article');
SELECT pg_temp.assert_true(can_review_articles() AND NOT has_party_permission('news.publish'),'Editor gets article permission only');
SELECT pg_temp.assert_true((SELECT count(*)=1 FROM notifications WHERE reference_id=current_setting('test.article') AND type='article_submitted'),'Editor receives one submission notification');
SELECT pg_temp.assert_true(pg_temp.denied(format('SELECT review_member_article(%s,''rejected'','''')',current_setting('test.article'))),'Changes require feedback');
SELECT review_member_article(current_setting('test.article')::bigint,'rejected','Please clarify your introduction.');
SELECT set_config('request.jwt.claim.sub',current_setting('test.author'),true);
SELECT pg_temp.assert_true((SELECT status='rejected' AND review_note<>'' AND NOT is_published FROM news_items WHERE id=current_setting('test.article')::bigint),'Rejection stores feedback privately');
SELECT pg_temp.assert_true((SELECT count(*)=1 FROM notifications WHERE reference_id=current_setting('test.article') AND type='article_changes_requested'),'Author receives feedback notification');
SELECT save_member_article(current_setting('test.article')::bigint,'Rollback test article','This article has a clarified introduction, and exists only in a rollback.','',true);
SELECT set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
SELECT pg_temp.assert_true((SELECT count(*)=2 FROM notifications WHERE reference_id=current_setting('test.article') AND type='article_submitted'),'Owner notified on original and revised submission');
SELECT set_config('request.jwt.claim.sub',current_setting('test.editor'),true);
SELECT review_member_article(current_setting('test.article')::bigint,'published','');
SELECT pg_temp.assert_true(pg_temp.denied(format('SELECT review_member_article(%s,''published'','''')',current_setting('test.article'))),'Duplicate review blocked');
RESET ROLE;
SET LOCAL ROLE anon;
SELECT set_config('request.jwt.claim.sub','',true);
SELECT pg_temp.assert_true(NOT EXISTS(SELECT 1 FROM news_items WHERE id=current_setting('test.editor_article')::bigint),'Anonymous cannot read submitted article');
SELECT pg_temp.assert_true((SELECT count(*)=1 FROM news_items WHERE id=current_setting('test.article')::bigint AND status='published' AND is_published),'Approved article visible publicly');
RESET ROLE;
UPDATE party_appointments SET ended_at=now() WHERE profile_id=current_setting('test.editor')::uuid;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',current_setting('test.editor'),true);
SELECT pg_temp.assert_true(NOT can_review_articles(),'Ending appointment removes editor access');
RESET ROLE;
ROLLBACK;
