-- Media Albums Feature (Corrected)
-- Adds album categorization to media gallery with proper RLS

-- 1. CREATE ALBUMS TABLE
CREATE TABLE IF NOT EXISTS public.media_albums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    name_ne TEXT,
    description TEXT,
    cover_image_url TEXT,
    created_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. ADD ALBUM_ID TO MEDIA_GALLERY
ALTER TABLE public.media_gallery 
ADD COLUMN IF NOT EXISTS album_id BIGINT REFERENCES public.media_albums(id);

-- 3. ADD UPLOADER TRACKING
ALTER TABLE public.media_gallery 
ADD COLUMN IF NOT EXISTS uploaded_by UUID REFERENCES public.profiles(id);

-- 4. ENABLE RLS ON ALBUMS
ALTER TABLE public.media_albums ENABLE ROW LEVEL SECURITY;

-- 5. CREATE TRIGGER TO AUTO-SET uploaded_by
CREATE OR REPLACE FUNCTION public.set_media_uploaded_by()
RETURNS trigger AS $$
BEGIN
  IF NEW.uploaded_by IS NULL THEN
    NEW.uploaded_by := auth.uid();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS set_media_uploaded_by_trigger ON public.media_gallery;

CREATE TRIGGER set_media_uploaded_by_trigger
BEFORE INSERT ON public.media_gallery
FOR EACH ROW
EXECUTE FUNCTION public.set_media_uploaded_by();

-- 6. DROP ALL EXISTING POLICIES (idempotent)
DROP POLICY IF EXISTS "Public read access" ON public.media_gallery;
DROP POLICY IF EXISTS "Admin write access media" ON public.media_gallery;
DROP POLICY IF EXISTS "Media: privileged manage all" ON public.media_gallery;
DROP POLICY IF EXISTS "Media: public read" ON public.media_gallery;
DROP POLICY IF EXISTS "Media: upload" ON public.media_gallery;
DROP POLICY IF EXISTS "Media: update own" ON public.media_gallery;
DROP POLICY IF EXISTS "Media: update any (admin/yantrik)" ON public.media_gallery;
DROP POLICY IF EXISTS "Media: delete (admin/admin_party)" ON public.media_gallery;
DROP POLICY IF EXISTS "Media: delete (admin/admin_party/yantrik)" ON public.media_gallery;

DROP POLICY IF EXISTS "Albums: public read" ON public.media_albums;
DROP POLICY IF EXISTS "Albums: create" ON public.media_albums;
DROP POLICY IF EXISTS "Albums: merge (admin/yantrik)" ON public.media_albums;
DROP POLICY IF EXISTS "Albums: manage (admin/yantrik)" ON public.media_albums;

-- ============================================
-- 7. ALBUMS RLS POLICIES
-- ============================================

-- 7a. Anyone can read albums
CREATE POLICY "Albums: public read"
ON public.media_albums
FOR SELECT
USING (true);

-- 7b. CC+ can create albums
CREATE POLICY "Albums: create"
ON public.media_albums
FOR INSERT
TO authenticated
WITH CHECK (
    public.get_user_role(auth.uid()) IN (
        'central_committee', 'board', 'admin_party', 'yantrik', 'admin'
    )
);

-- 7c. Only admin and yantrik can update/delete any album (for merging)
CREATE POLICY "Albums: manage (admin/yantrik)"
ON public.media_albums
FOR ALL
TO authenticated
USING (
    public.get_user_role(auth.uid()) IN ('admin', 'yantrik')
)
WITH CHECK (
    public.get_user_role(auth.uid()) IN ('admin', 'yantrik')
);

-- ============================================
-- 8. MEDIA GALLERY RLS POLICIES
-- ============================================

-- 8a. Public read - everyone can see media
CREATE POLICY "Media: public read"
ON public.media_gallery
FOR SELECT
USING (true);

-- 8b. CC+ can upload (insert) media
CREATE POLICY "Media: upload"
ON public.media_gallery
FOR INSERT
TO authenticated
WITH CHECK (
    public.get_user_role(auth.uid()) IN (
        'central_committee', 'board', 'admin_party', 'yantrik', 'admin'
    )
);

-- 8c. CC/board can update ONLY their own uploads
CREATE POLICY "Media: update own"
ON public.media_gallery
FOR UPDATE
TO authenticated
USING (
    uploaded_by = auth.uid()
    AND public.get_user_role(auth.uid()) IN (
        'central_committee', 'board', 'admin_party', 'yantrik', 'admin'
    )
)
WITH CHECK (
    uploaded_by = auth.uid()
);

-- 8d. Admin/yantrik/admin_party can update ANY media
CREATE POLICY "Media: update any (admin/yantrik)"
ON public.media_gallery
FOR UPDATE
TO authenticated
USING (
    public.get_user_role(auth.uid()) IN ('admin', 'yantrik', 'admin_party')
)
WITH CHECK (true);

-- 8e. Admin/admin_party/yantrik can delete ANY media
CREATE POLICY "Media: delete (admin/admin_party/yantrik)"
ON public.media_gallery
FOR DELETE
TO authenticated
USING (
    public.get_user_role(auth.uid()) IN ('admin', 'admin_party', 'yantrik')
);

-- ============================================
-- 9. CREATE DEFAULT ALBUM
-- ============================================
INSERT INTO public.media_albums (name, name_ne, description)
VALUES ('General', 'सामान्य', 'Uncategorized media items')
ON CONFLICT DO NOTHING;

-- 10. NOTIFY SCHEMA RELOAD
NOTIFY pgrst, 'reload schema';
