-- Admin CMS Schema

-- 1. Site Settings (Key-Value Store for Global/Page Content)
CREATE TABLE IF NOT EXISTS public.site_settings (
    key TEXT PRIMARY KEY, -- e.g., 'global', 'hero', 'about', 'contact'
    content JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by UUID REFERENCES auth.users(id)
);

-- 2. News Items
CREATE TABLE IF NOT EXISTS public.news_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    source TEXT NOT NULL, -- e.g. "OnlineKhabar"
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    type TEXT NOT NULL CHECK (type IN ('Article', 'Video', 'Interview')),
    link TEXT NOT NULL, -- External URL or Internal Path
    image_url TEXT,
    is_published BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_by UUID REFERENCES auth.users(id)
);

-- 3. Media Gallery (Photos & Videos)
CREATE TABLE IF NOT EXISTS public.media_gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('image', 'video')),
    url TEXT NOT NULL, -- YouTube URL or Image URL
    caption TEXT,
    thumbnail_url TEXT, -- For videos or optimized images
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_by UUID REFERENCES auth.users(id)
);

-- 4. User Profiles & Roles
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Enable RLS
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 6. Policies

-- Profiles: Users can read their own profile. Admins can read all.
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true); -- Simplified for now, or strict: auth.uid() = id
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- CMS Content: Public Read
CREATE POLICY "Public read access" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Public read access" ON public.news_items FOR SELECT USING (is_published = true);
CREATE POLICY "Public read access" ON public.media_gallery FOR SELECT USING (true);

-- CMS Content: Admin Write Only
-- We need a helper to check if user is admin. unique to Supabase logic often involves a joined check or claims.
-- For simplicity in SQL policies without custom claims:
-- USING (auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'admin'))

CREATE POLICY "Admin write access settings" ON public.site_settings FOR ALL USING (
    auth.role() = 'authenticated' AND 
    auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'admin')
);

CREATE POLICY "Admin write access news" ON public.news_items FOR ALL USING (
    auth.role() = 'authenticated' AND 
    auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'admin')
);

CREATE POLICY "Admin write access media" ON public.media_gallery FOR ALL USING (
    auth.role() = 'authenticated' AND 
    auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'admin')
);

-- 7. Trigger for New Users
-- Automatically create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'user');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 8. Seed Data (Migrated content...)
-- ... (Existing seed insertions) ...
-- Seed Admin User (Optional/Manual):
-- INSERT INTO public.profiles (id, email, role) VALUES ('<UUID>', 'admin@pragatishil.org', 'admin');


-- 'global' settings (Nav, Brand, Footer, Contact, Social) - Simplified structure matching SiteSettings interface roughly
INSERT INTO public.site_settings (key, content)
VALUES
('global', '{
    "nav": {
        "home": { "en": "Home", "ne": "गृहपृष्ठ" },
        "news": { "en": "News", "ne": "समाचार" },
        "media": { "en": "Media", "ne": "मिडिया" },
        "about": { "en": "About", "ne": "हाम्रो बारेमा" },
        "contact": { "en": "Contact", "ne": "सम्पर्क" },
        "members": { "en": "Members", "ne": "सदस्यहरू" },
        "join": { "en": "Join Movement", "ne": "अभियानमा जोडिनुहोस्" },
        "brand": {
             "firstEn": "Pragatishil", "secondEn": "Loktantrik",
             "firstNe": "प्रगतिशील", "secondNe": "लोकतान्त्रिक"
        }
    },
    "contact": {
        "address": "Baneshwor, Kathmandu, Nepal",
        "email": "info@pragatishil.org.np",
        "phone": "+977-1-4XXXXXX"
    },
    "social": [
        { "name": "Facebook", "icon": "facebook", "url": "https://facebook.com" },
        { "name": "Twitter", "icon": "twitter", "url": "https://twitter.com" },
        { "name": "YouTube", "icon": "youtube", "url": "https://youtube.com" },
        { "name": "Instagram", "icon": "instagram", "url": "https://instagram.com" },
        { "name": "TikTok", "icon": "tiktok", "url": "https://tiktok.com" }
    ],
    "footer": {
        "taglineNe": "नेपाली माटो, हाम्रो बाटो",
        "taglineEn": "Building a just, progressive and prosperous Nepal from our own soil."
    }
}'::jsonb),

('hero', '{
    "pillNe": "Pragatishil Loktantrik",
    "titleNe": "प्रगतिशील लोकतान्त्रिक पार्टीमा स्वागत छ",
    "titleEn": "Welcome to Pragatishil Loktantrik Party",
    "subtitleNe": "नेपाली माटो, हाम्रो बाटो",
    "subtitleEnLine1": "Progressive socialist, democratic alternative for Nepal.",
    "subtitleEnLine2": "Rooted in Nepali soil, walking our own path with justice, inclusion and good governance.",
    "ctaPrimary": "Join the Movement",
    "ctaSecondary": "View Members"
}'::jsonb),

('vision', '{
    "titleNe": "हाम्रो दृष्टिकोण",
    "titleEn": "Our Vision",
    "textNe": "हामी एक समतामूलक समाजको परिकल्पना गर्छौं जहाँ प्रत्येक नागरिकले समान अवसर, न्याय र सम्मान पाउँछन्।",
    "textEn": "We envision an equitable society where every citizen enjoys equal opportunities, justice, and dignity.",
    "pillars": [
        { "titleNe": "प्रगतिशील समाजवाद", "titleEn": "Progressive Socialism", "descEn": "Our guiding ideology – combining social justice, democracy and modern development.", "icon": "🤝" },
        { "titleNe": "लोकतन्त्रिक मूल्यहरू", "titleEn": "Democratic Values", "descEn": "Multi-party democracy, civil liberties, rule of law and accountable institutions.", "icon": "🗳️" },
        { "titleNe": "समावेशी नेतृत्व", "titleEn": "Inclusive Leadership", "descEn": "Youth, women and marginalized communities at every level of party leadership.", "icon": "👥" },
        { "titleNe": "आधुनिक एजेन्डा", "titleEn": "Gen Z & Modern Agendas", "descEn": "Addressing the concerns of new generations – jobs, innovation, climate, digital rights.", "icon": "🚀" },
        { "titleNe": "संघीयता र जिम्मेवार राष्ट्रवाद", "titleEn": "Federalism & Nationalism", "descEn": "Strong federalism and national unity, opposing ultra-nationalism and exclusion.", "icon": "🇳🇵" },
        { "titleNe": "भ्रष्टाचार विरुद्ध शून्य सहनशीलता", "titleEn": "End Corruption", "descEn": "Transparent governance, clean politics and strict action against corruption.", "icon": "🚫" }
    ]
}'::jsonb),

('about', '{
    "titleNe": "हाम्रो बारेमा",
    "titleEn": "About Us",
    "descriptionNe": "प्रगतिशील लोकतान्त्रिक पार्टी नेपालको राजनीतिक परिदृश्यमा एक वैकल्पिक शक्तिको रूपमा उदाएको छ। हामी परम्परागत राजनीतिको सीमालाई तोड्दै विज्ञान, प्रविधि र मानवीय मूल्यमान्यतामा आधारित नयाँ राजनीतिक संस्कृतिको विकास गर्न चाहन्छौं।",
    "descriptionEn": "The Pragatishil Loktantrik Party (PDP) has emerged as an alternative force in Nepal''s political landscape. Breaking the boundaries of traditional politics, we aim to develop a new political culture based on science, technology, and human values."
}'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- Seed News
INSERT INTO public.news_items (title, source, date, type, link, image_url)
VALUES
('वैचारिक खडेरीको कालखण्ड (A Period of Ideological Drought)', 'OnlineKhabar', '2024-08-25', 'Article', 'https://www.onlinekhabar.com/2025/08/1743950/a-period-of-ideological-drought', 'https://www.onlinekhabar.com/wp-content/uploads/2025/08/Baicharik-Khareri-1024x683.jpg'),
('Pragatishil Party Manifesto Launch', 'Kantipur', '2024-06-15', 'Article', 'https://ekantipur.com', 'https://picsum.photos/800/600?random=10'),
('Chairman Interview: The Way Forward', 'The Kathmandu Post', '2024-07-01', 'Interview', 'https://kathmandupost.com', 'https://picsum.photos/800/600?random=11');

-- Seed Videos
INSERT INTO public.media_gallery (type, url, caption)
VALUES
('video', 'https://www.youtube.com/embed/XusiP06Z_lg', 'Pragatishil Party Video 1'),
('video', 'https://www.youtube.com/embed/2-SkP3SIrKk', 'Pragatishil Party Video 2'),
('video', 'https://www.youtube.com/embed/TUMNWhBYfxs', 'Pragatishil Party Video 3');

-- ... (Existing Seed insertions)

-- 9. Storage Buckets & Policies
-- Note: 'storage' schema usually exists in Supabase.
-- Attempt to create 'media' bucket if not exists (requires permissions or manual creation)
INSERT INTO storage.buckets (id, name, public)
VALUES ('media', 'media', true)
ON CONFLICT (id) DO NOTHING;

-- Policy: Allow Public Read for 'media' bucket
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'media');

-- Policy: Allow Authenticated Users (Admins) to Upload
CREATE POLICY "Auth Users Upload" ON storage.objects FOR INSERT WITH CHECK (
    bucket_id = 'media' AND auth.role() = 'authenticated'
);

-- Policy: Allow Authenticated Users (Admins) to Delete
CREATE POLICY "Auth Users Delete" ON storage.objects FOR DELETE USING (
    bucket_id = 'media' AND auth.role() = 'authenticated'
);
