import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Website Terms / \u0935\u0947\u092c\u0938\u093e\u0907\u091f \u092a\u094d\u0930\u092f\u094b\u0917\u0915\u093e \u0938\u0930\u094d\u0924\u0939\u0930\u0942" };
const sections = [["Website purpose", "This website provides information about Pragatishil Loktantrik Party and a form to submit membership information. Google sign-in establishes a website account. Contact the party for membership eligibility, verification, responsibilities, and current party rules."], ["Submitting an application", "Submit your own accurate information and review it before sending. Do not impersonate another person, submit another person’s identity documents without permission, or upload unlawful content. Automated ID scanning is a convenience and may make mistakes; you are responsible for checking your entries."], ["Account and website use", "Keep your Google account secure. Do not attempt to access someone else’s records, bypass access controls, abuse upload or scanning features, or interfere with the website. If you notice a mistake or account problem, contact the party."], ["Information and availability", "Website content and features may change, and service interruptions can occur. Contact the party to confirm membership status or important information. Do not rely on an automated form response as proof of a separate legal, electoral, or administrative entitlement."], ["Privacy and contact", "Please read the Privacy Policy before submitting personal information. Questions about website use or your application can be sent to pragatishilloktantrik@gmail.com. Do not include passwords or identity-document images in email."], ["नेपालीमा मुख्य जानकारी", "आफ्नै सही विवरण मात्र भर्नुहोस् र पठाउनुअघि जाँच गर्नुहोस्। Google लगइनले वेबसाइट खाता बनाउँछ। सदस्यताको योग्यता, प्रमाणीकरण र दलका नियमबारे दलसँग सम्पर्क गर्नुहोस्। अरूको खाता वा निजी विवरणमा अनधिकृत पहुँच नगर्नुहोस्। व्यक्तिगत विवरण पठाउनुअघि गोपनीयता नीति पढ्नुहोस्।"]];

export default function Page() {
 return <main className="mx-auto max-w-3xl px-6 py-12 text-slate-900"><article className="rounded-2xl bg-white p-6 shadow-sm sm:p-10"><h1 className="text-3xl font-bold">Website Terms / वेबसाइट प्रयोगका सर्तहरू</h1><p className="mt-3 text-sm text-slate-600">Updated: 7 October 2026 · Pragatishil Loktantrik Party</p>{sections.map(([heading,body]) => <section key={heading} className="mt-8"><h2 className="text-xl font-semibold">{heading}</h2><p className="mt-3 leading-7">{body}</p></section>)}<nav className="mt-10 flex gap-6 text-blue-800 underline"><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Website Terms</Link><Link href="/join">Membership form</Link></nav></article></main>;
}
